# Generated by Django 5.2.4 on 2025-07-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('model_name', models.CharField(choices=[('mistralai/Mistral-7B-Instruct-v0.1', 'Mistral 7B Instruct v0.1'), ('mistralai/Mistral-7B-Instruct-v0.2', 'Mistral 7B Instruct v0.2'), ('mistralai/Mistral-7B-Instruct-v0.3', 'Mistral 7B Instruct v0.3'), ('mistralai/Mixtral-8x7B-Instruct-v0.1', 'Mixtral 8x7B Instruct v0.1'), ('mistralai/Mixtral-8x22B-Instruct-v0.1', 'Mixtral 8x22B Instruct v0.1'), ('meta-llama/Llama-2-7b-chat-hf', 'Llama 2 7B Chat'), ('meta-llama/Llama-2-13b-chat-hf', 'Llama 2 13B Chat'), ('meta-llama/Llama-2-70b-chat-hf', 'Llama 2 70B Chat'), ('meta-llama/Meta-Llama-3-8B-Instruct', 'Llama 3 8B Instruct'), ('meta-llama/Meta-Llama-3-70B-Instruct', 'Llama 3 70B Instruct'), ('NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO', 'Nous Hermes 2 Mixtral 8x7B'), ('teknium/OpenHermes-2.5-Mistral-7B', 'OpenHermes 2.5 Mistral 7B'), ('togethercomputer/RedPajama-INCITE-7B-Chat', 'RedPajama INCITE 7B Chat'), ('Qwen/Qwen1.5-7B-Chat', 'Qwen 1.5 7B Chat'), ('Qwen/Qwen1.5-14B-Chat', 'Qwen 1.5 14B Chat'), ('Qwen/Qwen1.5-72B-Chat', 'Qwen 1.5 72B Chat')], default='mistralai/Mistral-7B-Instruct-v0.1', max_length=200)),
                ('max_tokens', models.IntegerField(default=500, help_text='Maximum tokens for response')),
                ('temperature', models.FloatField(default=0.7, help_text='Temperature for response randomness (0.0-1.0)')),
                ('top_p', models.FloatField(default=0.9, help_text='Top-p sampling parameter (0.0-1.0)')),
                ('repetition_penalty', models.FloatField(default=1.0, help_text='Repetition penalty (1.0 = no penalty)')),
                ('is_active', models.BooleanField(default=False, help_text='Use this configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model Configuration',
                'verbose_name_plural': 'AI Model Configurations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('together', 'Together.ai'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('cohere', 'Cohere'), ('huggingface', 'Hugging Face')], max_length=20, unique=True)),
                ('api_key', models.CharField(help_text='API key (encrypted in production)', max_length=500)),
                ('api_url', models.URLField(help_text='API endpoint URL')),
                ('is_active', models.BooleanField(default=False, help_text='Use this API configuration')),
                ('max_requests_per_minute', models.IntegerField(default=60, help_text='Rate limiting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Key Configuration',
                'verbose_name_plural': 'API Key Configurations',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prompt_type', models.CharField(choices=[('system', 'System Prompt'), ('assistant', 'Assistant Persona'), ('knowledge_base', 'Knowledge Base Context'), ('fallback', 'Fallback Response')], default='system', max_length=20)),
                ('content', models.TextField(help_text='The prompt content')),
                ('is_active', models.BooleanField(default=False, help_text='Use this prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Prompt',
                'verbose_name_plural': 'System Prompts',
                'ordering': ['prompt_type', '-updated_at'],
            },
        ),
    ]
