# Generated by Django 5.2.4 on 2025-07-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_aimodelconfig_apikeyconfig_systemprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('schedules', 'Расписание'), ('documents', 'Документы'), ('scholarships', 'Стипендии'), ('exams', 'Экзамены'), ('administration', 'Администрация'), ('general', 'Общие'), ('fees', 'Оплата'), ('dormitory', 'Общежитие'), ('library', 'Библиотека'), ('services', 'Услуги')], default='general', max_length=20)),
                ('keywords', models.TextField(help_text='Ключевые слова для поиска, разделенные пробелами')),
                ('source', models.CharField(choices=[('manual', 'Ручное добавление'), ('ai_generated', 'Создано AI'), ('search_based', 'На основе поиска')], default='manual', max_length=20)),
                ('language', models.CharField(default='ru', max_length=10)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base Entry',
                'verbose_name_plural': 'Knowledge Base Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('language', models.CharField(default='ru', max_length=10)),
                ('results_found', models.BooleanField(default=False)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('should_add_to_kb', models.BooleanField(default=False)),
                ('added_to_kb', models.BooleanField(default=False)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
