# Generated by Django 5.2.4 on 2025-07-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_knowledgebaseentry_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='kb_entries_used_new',
            field=models.ManyToManyField(blank=True, related_name='request_logs', to='agent.knowledgebaseentry'),
        ),
    ]
