# Generated by Django 5.2.4 on 2025-07-19 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_requestlog_kb_entries_used_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('banned_word', 'Запрещенное слово'), ('pattern', 'Шаблон (regex)'), ('phrase', 'Запрещенная фраза')], default='banned_word', max_length=20)),
                ('content', models.TextField(help_text='Слово, фраза или regex-шаблон для фильтрации')),
                ('severity', models.CharField(choices=[('low', 'Низкая (предупреждение)'), ('medium', 'Средняя (цензура)'), ('high', 'Высокая (блокировка)')], default='medium', max_length=10)),
                ('replacement', models.CharField(blank=True, help_text='Замена для цензурируемого контента (по умолчанию: ***)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to_ai', models.BooleanField(default=True, help_text='Применять к ответам AI')),
                ('applies_to_faq', models.BooleanField(default=True, help_text='Применять к результатам поиска FAQ')),
                ('applies_to_input', models.BooleanField(default=True, help_text='Применять к пользовательскому вводу')),
                ('language', models.CharField(default='all', help_text='Язык (ru/en/kk/all)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Filter',
                'verbose_name_plural': 'Content Filters',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_content', models.TextField()),
                ('modified_content', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('censored', 'Цензурировано'), ('blocked', 'Заблокировано'), ('warned', 'Предупреждение')], max_length=20)),
                ('content_type', models.CharField(help_text='ai_response/faq_result/user_input', max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filter_matched', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.contentfilter')),
            ],
            options={
                'verbose_name': 'Moderation Log',
                'verbose_name_plural': 'Moderation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
