# Generated by Django 5.2.4 on 2025-07-20 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_analytics_eventschedule_notification_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, help_text='Название беседы', max_length=200),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('voice', 'Voice'), ('image', 'Image')], max_length=10),
        ),
        migrations.CreateModel(
            name='ChatProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название проекта', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Описание проекта')),
                ('project_type', models.CharField(choices=[('academic', 'Учёба'), ('research', 'Исследования'), ('personal', 'Личное'), ('work', 'Работа'), ('general', 'Общее')], default='general', max_length=20)),
                ('color', models.CharField(default='#0D1B2A', help_text='Цвет темы (hex)', max_length=7)),
                ('icon', models.CharField(default='fas fa-folder', help_text='FontAwesome иконка', max_length=20)),
                ('custom_prompt', models.TextField(blank=True, help_text='Специальные инструкции для AI')),
                ('allowed_file_types', models.JSONField(default=list, help_text='Разрешенные типы файлов')),
                ('max_context_messages', models.IntegerField(default=20, help_text='Максимум сообщений в контексте')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Project',
                'verbose_name_plural': 'Chat Projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='agent.chatproject'),
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='Краткое содержание беседы')),
                ('key_topics', models.JSONField(default=list, help_text='Основные темы обсуждения')),
                ('action_items', models.JSONField(default=list, help_text='Задачи и действия')),
                ('message_count', models.IntegerField(default=0)),
                ('date_range_start', models.DateTimeField()),
                ('date_range_end', models.DateTimeField()),
                ('generated_by', models.CharField(default='ai', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.chatproject')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='agent.chatsession')),
            ],
            options={
                'verbose_name': 'Conversation Summary',
                'verbose_name_plural': 'Conversation Summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('attachment_type', models.CharField(choices=[('image', 'Изображение'), ('document', 'Документ'), ('audio', 'Аудио'), ('video', 'Видео'), ('file', 'Файл')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('analysis_result', models.JSONField(blank=True, help_text='Результат анализа AI', null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Извлеченный текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='agent.chatmessage')),
            ],
            options={
                'verbose_name': 'Message Attachment',
                'verbose_name_plural': 'Message Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', '😊 Радостное'), ('neutral', '😐 Нейтральное'), ('sad', '😢 Грустное'), ('angry', '😠 Злое'), ('excited', '🤩 Взволнованное'), ('confused', '😕 Смущенное'), ('frustrated', '😤 Расстроенное'), ('calm', '😌 Спокойное')], max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='Уверенность определения (0-1)')),
                ('detected_keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.chatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_tracking', to='agent.chatsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Mood',
                'verbose_name_plural': 'User Moods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice/%Y/%m/%d/')),
                ('duration', models.FloatField(help_text='Длительность в секундах')),
                ('transcription', models.TextField(blank=True, help_text='Расшифровка речи')),
                ('confidence', models.FloatField(default=0.0, help_text='Уверенность распознавания (0-1)')),
                ('status', models.CharField(choices=[('uploading', 'Загружается'), ('transcribing', 'Распознается'), ('completed', 'Готово'), ('failed', 'Ошибка')], default='uploading', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('detected_language', models.CharField(blank=True, max_length=10)),
                ('emotion', models.CharField(blank=True, help_text='Определенная эмоция', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('chat_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_data', to='agent.chatmessage')),
            ],
            options={
                'verbose_name': 'Voice Message',
                'verbose_name_plural': 'Voice Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
